### ISSUE TITLE
Research automated accessibility testing software

### ISSUE THREAD

**Issue by marianntlu** [marianntapfer/masterThesis#4]
GanttStart: 2022-04-18
GanttDue: 2022-05-21

https://www.w3.org/developers/tools/

Software for testing: - both suitable to use in CI pipeline, works with node and js and is free
https://github.com/dequelabs/axe-core
https://github.com/pa11y/pa11y-ci

**Comment by marianntapfer** [comment]
Other companies using these tools: 
Pa11y CI: https://grafana.com/accessibility/, https://www.youtube.com/watch?v=pBwuMbtvVnk
