### ISSUE TITLE
Pre test questionnaire

### ISSUE THREAD

**Issue by marianntlu** [marianntapfer/masterThesis#6]
GanttStart: 2022-05-22
GanttDue: 2022-05-30

Questionnaire
Developers knowledge about accessibility
How do they evaluate CUI in terms of accessibility
Evaluation 
Accessibility score for CUI 
- decide on compliance criteria AA??
- scope - what will be tested - CUI in storybook, main views in the webapp also?

**Comment by marianntapfer** [comment]
Posted to accessibility and fe-development related channels. Asked one of the designers to share in design channels. 
fe-devs: 212in, convention-ui: 124 in, accessibility 31 in + private channel - there might be some overlap in those channels
