### ISSUE TITLE
Add tests to one of the services 

### ISSUE THREAD

**Issue by marianntlu** [marianntapfer/masterThesis#9]
GanttStart: 2022-05-30
GanttDue: 2022-06-06

From the researched and presented option choose and implement one

**Comment by marianntapfer** [comment]
Using [a11y addon](https://github.com/storybookjs/storybook/tree/next/code/addons/a11y) in storybook that uses [Axe Javascript Accessibility API](https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#overview) to find vialoations

these are the rules it checks against - verify that..
